# Generated by Django 4.0.3 on 2022-04-18 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無しのycu', max_length=200, verbose_name='名前')),
                ('text', models.TextField(verbose_name='スレリプ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thread.topic', verbose_name='対称スレッド')),
            ],
        ),
    ]
