# Generated by Django 4.0.3 on 2022-04-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0005_alter_comment_target'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
    ]
