# Generated by Django 4.0.3 on 2022-04-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0006_delete_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name=''),
        ),
    ]
